CREATE TABLE IF NOT EXISTS Word(
	Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	Word TEXT NOT NULL UNIQUE COLLATE NOCASE,
	CreatedBy TEXT NOT NULL DEFAULT 'Anonymous',
	CreatedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	IsExpired INTEGER NOT NULL DEFAULT 0,
	ExpiredAt TEXT,
	IsBlocked INTEGER NOT NULL DEFAULT 0
)