CREATE TABLE IF NOT EXISTS Word(
	Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	Word TEXT NOT NULL UNIQUE COLLATE NOCASE,
	AddedBy TEXT NOT NULL DEFAULT 'Anonymous',
	AddedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	IsUsed INTEGER NOT NULL DEFAULT 0,
	UsedAt TEXT,
	Blocked INTEGER NOT NULL DEFAULT 0
)